server:
  port: 8080

spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://192.168.1.113:3306/archer?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.archer.ats.entity


#showSql
logging:
  level:
    com:
      example:
        mapper: debug